=== armish/enzymeportal/enzyme-portal/ep-domain/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://ebi.ac.uk/ep/config" xmlns:ep="http://ebi.ac.uk/ep/config" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Domain" type="ep:Domain"/>
	<xs:complexType name="Domain">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SearchFieldList" type="ep:SearchFieldList" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ResultFieldList" type="ep:ResultFieldList" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="EnzymeRelatedDomains" type="ep:EnzymeRelatedDomains"/>
	<xs:complexType name="EnzymeRelatedDomains">
		<xs:sequence>
			<xs:element name="Domain" type="ep:Domain" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Field" type="ep:Field"/>
	<xs:complexType name="Field">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ResultField" type="ep:ResultField"/>
	<xs:complexType name="ResultField">
		<xs:complexContent>
			<xs:extension base="ep:Field">
				<xs:sequence>
					<xs:element name="resultvalue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ResultFieldList" type="ep:ResultFieldList"/>
	<xs:complexType name="ResultFieldList">
		<xs:sequence>
			<xs:element name="ResultField" type="ep:ResultField" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="SearchField" type="ep:SearchField"/>
	<xs:complexType name="SearchField">
		<xs:complexContent>
			<xs:extension base="ep:Field">
				<xs:sequence>
					<xs:element name="searchvalue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="SearchFieldList" type="ep:SearchFieldList"/>
	<xs:complexType name="SearchFieldList">
		<xs:sequence>
			<xs:element name="SearchField" type="ep:SearchField" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== armish/enzymeportal/ep-core/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<ep:EnzymeRelatedDomains xmlns:ep="http://ebi.ac.uk/enzymeportal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ebi.ac.uk/enzymeportal config.xsd ">
  <Domain>
    <id>intenz</id>
    <SearchFieldList>
      <SearchField>
        <id>name</id>
      </SearchField>
      <SearchField>
        <id>synonym</id>
      </SearchField>
      <SearchField>
        <id>systematic_name</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
  <Domain>
    <id>rhea</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>chebiidequation</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
  <Domain>
    <id>reactome</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
  <Domain>
    <id>chebi</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
      <SearchField>
        <id>synonym</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
  <Domain>
    <id>chembl-compound</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
  <Domain>
    <id>pdbe</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
      <SearchField>
        <id>keywords</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
<Domain>
    <id>uniprot</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>descRecName</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
      <SearchField>
        <id>keywords</id>
      </SearchField>
      <SearchField>
        <id>organism_species</id>
      </SearchField>
      <SearchField>
        <id>organism_scientific_name</id>
      </SearchField>
      <SearchField>
        <id>organism_lineage</id>
      </SearchField>
      <SearchField>
        <id>organism_host_species</id>
      </SearchField>      
      <SearchField>
        <id>dbRefProp_EMBL_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblBacteria_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblFungi_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblMetazoa_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblPlants_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblProtists_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_Ensembl_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_GeneFarm_family_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_WormBase_protein_sequence_ID </id>
      </SearchField>
    </SearchFieldList>
    <!--acc, descSubName, gene_primary_name, id, organism_scientific_name, sequence_length, status-->
    <ResultFieldList>
      <ResultField>
        <id>id</id>
      </ResultField>
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>descRecName</id>
      </ResultField>
      <ResultField>
        <id>descSubName</id>
      </ResultField>
      <ResultField>
        <id>organism_scientific_name</id>
      </ResultField>
      <ResultField>
        <id>sequence_length</id>
      </ResultField>
      <ResultField>
        <id>status</id>
      </ResultField>
    </ResultFieldList>
  </Domain>
</ep:EnzymeRelatedDomains>

=== armish/enzymeportal/enzyme-portal/ep-domain/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Contains the searchable and retrievable fields-->
<ep:EnzymeRelatedDomains xmlns:ep="http://ebi.ac.uk/ep/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ebi.ac.uk/ep/config config.xsd ">
  <Domain>
    <id>intenz</id>
    <SearchFieldList>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
      <SearchField>
        <id>synonym</id>
      </SearchField>
      <SearchField>
        <id>systematic_name</id>
      </SearchField>
      <SearchField>
        <id>reaction</id>
      </SearchField>
    </SearchFieldList>
    <ResultFieldList>
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>id</id>
      </ResultField>
      <ResultField>
        <id>UNIPROT</id>
      </ResultField>
    </ResultFieldList>
  </Domain>
  <Domain>
    <id>rhea</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>chebiidequation</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
    </SearchFieldList>
  </Domain>
  <Domain>
    <id>reactome</id>
    <SearchFieldList>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
      <SearchField>
        <id>organism</id>
      </SearchField>
    </SearchFieldList>
    <ResultFieldList>
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>id</id>
      </ResultField>
      <ResultField>
        <id>UNIPROT</id>
      </ResultField>
    </ResultFieldList>
  </Domain>
  <Domain>
    <id>chebi</id>
    <SearchFieldList>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
      <SearchField>
        <id>synonym</id>
      </SearchField>
      <SearchField>
        <id>charge</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
      <SearchField>
        <id>formula</id>
      </SearchField>
      <SearchField>
        <id>inchi</id>
      </SearchField>
      <SearchField>
        <id>inchikey</id>
      </SearchField>      
      <SearchField>
        <id>iupac_name</id>
      </SearchField>
      <SearchField>
        <id>mass</id>
      </SearchField>
      <SearchField>
        <id>secondary_accession_number</id>
      </SearchField>      
      <SearchField>
        <id>smiles</id>
      </SearchField>
    </SearchFieldList>
    <ResultFieldList>
      <ResultField>
        <id>id</id>
      </ResultField>
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>UNIPROT</id>
      </ResultField>
    </ResultFieldList>
  </Domain>
  <Domain>
    <id>chembl-compound</id>
    <SearchFieldList>
      <SearchField>
        <id>compound_synonym</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
    </SearchFieldList>
    <ResultFieldList>
      <ResultField>
        <id>id</id>
      </ResultField>
  <!--
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>UNIPROT</id>
      </ResultField>
  -->
    </ResultFieldList>
  </Domain>
  <Domain>
    <id>pdbe</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
      <SearchField>
        <id>keywords</id>
      </SearchField>
      <SearchField>
        <id>name</id>
      </SearchField>
    </SearchFieldList>
    <ResultFieldList>
      <ResultField>
        <id>id</id>
      </ResultField>
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>UNIPROT</id>
      </ResultField>
    </ResultFieldList>
  </Domain>
<Domain>
    <id>uniprot</id>
    <SearchFieldList>
      <SearchField>
        <id>acc</id>
      </SearchField>
      <SearchField>
        <id>id</id>
      </SearchField>
      <SearchField>
        <id>descRecName</id>
      </SearchField>
      <SearchField>
        <id>description</id>
      </SearchField>
      <SearchField>
        <id>keywords</id>
      </SearchField>
      <SearchField>
        <id>organism_species</id>
      </SearchField>
      <SearchField>
        <id>organism_scientific_name</id>
      </SearchField>
      <SearchField>
        <id>organism_lineage</id>
      </SearchField>
      <SearchField>
        <id>organism_host_species</id>
      </SearchField>      
      <SearchField>
        <id>dbRefProp_EMBL_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblBacteria_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblFungi_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblMetazoa_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblPlants_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_EnsemblProtists_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_Ensembl_protein_sequence_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_GeneFarm_family_ID</id>
      </SearchField>
      <SearchField>
        <id>dbRefProp_WormBase_protein_sequence_ID </id>
      </SearchField>      
    </SearchFieldList>
    <!--acc, descSubName, gene_primary_name, id, organism_scientific_name, sequence_length, status-->
    <ResultFieldList>
      <ResultField>
        <id>id</id>
      </ResultField>
      <ResultField>
        <id>acc</id>
      </ResultField>
      <ResultField>
        <id>descRecName</id>
      </ResultField>
      <ResultField>
        <id>descSubName</id>
      </ResultField>
      <ResultField>
        <id>organism_scientific_name</id>
      </ResultField>
      <ResultField>
        <id>status</id>
      </ResultField>
    </ResultFieldList>
  </Domain>
</ep:EnzymeRelatedDomains>
